import type { Metadata } from "next";
import { Poltawski_Nowy, Poppins } from 'next/font/google'
import "./globals.css";
import { Web3Provider } from "@/components/Web3Provide";
import SessionWrapper from "@/components/SessionWrapper";


const nowy = Poltawski_Nowy({
  variable: '--font-nowy',
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

const poppins = Poppins({
  variable: '--font-pop',
  weight: ['300', '600'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${nowy.variable} antialiased bg-grayTint dark:bg-dark `}
      >
        <Web3Provider>
          <SessionWrapper>
            {children}
            </SessionWrapper>
        </Web3Provider>
      </body>
    </html>
  );
}